### ISSUE TITLE
ACTIVIDAD_1_MAPA_MENTAL

### ISSUE THREAD

**Issue by Litzy-lopez4** [SistemasTecTlaxiaco/actividad-1-mapa-mental-Litzy-lopez4#1]
[MAPA MENTAL1.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-mapa-mental-Litzy-lopez4/files/10704444/MAPA.MENTAL1.pdf)

**Comment by JoseABCruz** [comment]
Calificación 20%

Cumple con los criterios que establece la rúbrica
Uso de imágenes y colores 20%
Equilibrio y disposición del espacio. 20%
Énfasis/Relación. 20%
Conceptos 20%
Estructura 20%
Total= 100%/5 = 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
